# Generated by Django 3.0.8 on 2020-08-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200820_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
    ]
