# Generated by Django 3.0.8 on 2020-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200820_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='tax_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
