# Generated by Django 3.0.8 on 2020-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200803_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
