# Generated by Django 3.0.8 on 2020-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('kid', 'Kid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', 'Man')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(default=0.23, verbose_name='VAT'),
        ),
    ]
