# Generated by Django 3.0.8 on 2020-08-01 12:24

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200801_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, default='product_placeholder.png', null=True, upload_to=shop.models.get_image_path),
        ),
    ]
