# Generated by Django 3.0.8 on 2020-08-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0003_auto_20200803_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='started', max_length=100)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart')),
            ],
        ),
    ]
