# Generated by Django 3.0.8 on 2020-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='not_completed', max_length=150),
        ),
    ]
