# Generated by Django 3.0.8 on 2020-08-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200824_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
